#!/usr/bin/env python
import requests
import json
from requests.auth import HTTPBasicAuth
#
# Get First 20 Twitter user ids !
#
# GET https://api.twitter.com/1/users/lookup.json?user_id=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20&include_entities=true
#
url='https://api.twitter.com/1/users/lookup.json'
payload={"user_id":"1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20"}
r = requests.get(url, params=payload)
print json.dumps(r.headers,sort_keys=True,indent=2)
print json.dumps(r.json,sort_keys=True,indent=2)
'''
{
  "cache-control": "no-cache, no-store, must-revalidate, pre-check=0, post-check=0",
  "content-encoding": "gzip",
  "content-length": "3203",
  "content-type": "application/json; charset=utf-8",
  "date": "Sat, 23 Jun 2012 00:30:35 GMT",
  "etag": "\"f25e481c40991d2bb513e5518c62e449\"",
  "expires": "Tue, 31 Mar 1981 05:00:00 GMT",
  "last-modified": "Sat, 23 Jun 2012 00:30:35 GMT",
  "pragma": "no-cache",
  "server": "tfe",
  "set-cookie": "k=10.36.22.125.1340411435771806; path=/; expires=Sat, 30-Jun-12 00:30:35 GMT; domain=.twitter.com, guest_id=v1%3A134041143577659703; domain=.twitter.com; path=/; expires=Mon, 23-Jun-2014 12:30:35 GMT, _twitter_sess=BAh7CCIKZmxhc2hJQzonQWN0aW9uQ29udHJvbGxlcjo6Rmxhc2g6OkZsYXNo%250ASGFzaHsABjoKQHVzZWR7ADoPY3JlYXRlZF9hdGwrCAJbvxY4AToHaWQiJTZj%250AZWMxOWIwNDgwYTEzMjJjMGEwMzIwM2EzNGE3M2Vl--bbf4885a0a6350b67545c4e1e1d277db77407cb2; domain=.twitter.com; path=/; HttpOnly",
  "status": "200 OK",
  "vary": "Accept-Encoding",
  "x-frame-options": "SAMEORIGIN",
  "x-mid": "4039895474f7eab069829e848b6ffe53c9e5b60c",
  "x-ratelimit-class": "api",
  "x-ratelimit-limit": "150",
  "x-ratelimit-remaining": "144",
  "x-ratelimit-reset": "1340413192",
  "x-runtime": "0.14529",
  "x-transaction": "be28c01bd9a469f3",
  "x-transaction-mask": "a6183ffa5f8ca943ff1b53b5644ef114546a8e75"
}
[
  {
    "contributors_enabled": false,
    "created_at": "Tue Mar 21 21:02:31 +0000 2006",
    "default_profile": false,
    "default_profile_image": false,
    "description": "Farm boy from Nebraska. Husband and father. Co-founder of Twitter. Partner at @ObviousCorp",
    "favourites_count": 1969,
    "follow_request_sent": false,
    "followers_count": 1492447,
    "following": false,
    "friends_count": 1388,
    "geo_enabled": true,
    "id": 20,
    "id_str": "20",
    "is_translator": false,
    "lang": "en",
    "listed_count": 17836,
    "location": "San Francisco, CA, US",
    "name": "Evan Williams",
    "notifications": false,
    "profile_background_color": "e8e1d6",
    "profile_background_image_url": "http://a0.twimg.com/profile_background_images/407159427/x5e42bef1d791520b7e130629abceee8.png",
    "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/407159427/x5e42bef1d791520b7e130629abceee8.png",
    "profile_background_tile": true,
    "profile_image_url": "http://a0.twimg.com/profile_images/2200122186/_A_New_Age_of_Wonder_normal.jpg",
    "profile_image_url_https": "https://si0.twimg.com/profile_images/2200122186/_A_New_Age_of_Wonder_normal.jpg",
    "profile_link_color": "BA865E",
    "profile_sidebar_border_color": "746258",
    "profile_sidebar_fill_color": "8E6959",
    "profile_text_color": "F1A766",
    "profile_use_background_image": false,
    "protected": false,
    "screen_name": "ev",
    "show_all_inline_media": true,
    "status": {
      "contributors": null,
      "coordinates": null,
      "created_at": "Fri Jun 22 23:44:25 +0000 2012",
      "favorited": false,
      "geo": null,
      "id": 216315735943819264,
      "id_str": "216315735943819264",
      "in_reply_to_screen_name": "VirginAmerica",
      "in_reply_to_status_id": 215821105557016576,
      "in_reply_to_status_id_str": "215821105557016576",
      "in_reply_to_user_id": 12101862,
      "in_reply_to_user_id_str": "12101862",
      "place": null,
      "retweet_count": 2,
      "retweeted": false,
      "source": "<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
      "text": "@VirginAmerica It wasn't working at all on the way back, which was much nicer! Thanks for listening. ;) / @gogo",
      "truncated": false
    },
    "statuses_count": 6499,
    "time_zone": "Pacific Time (US & Canada)",
    "url": "http://t.co/C2HZiQ4",
    "utc_offset": -28800,
    "verified": true
  },
  {
    "contributors_enabled": false,
    "created_at": "Tue Mar 21 21:01:35 +0000 2006",
    "default_profile": true,
    "default_profile_image": false,
    "description": "Trazzler, Reston, Syracuse University, Sandwich",
    "favourites_count": 14,
    "follow_request_sent": false,
    "followers_count": 12792,
    "following": false,
    "friends_count": 207,
    "geo_enabled": true,
    "id": 18,
    "id_str": "18",
    "is_translator": false,
    "lang": "en",
    "listed_count": 106,
    "location": "San Francisco, CA",
    "name": "Adam Rugel",
    "notifications": false,
    "profile_background_color": "C0DEED",
    "profile_background_image_url": "http://a0.twimg.com/images/themes/theme1/bg.png",
    "profile_background_image_url_https": "https://si0.twimg.com/images/themes/theme1/bg.png",
    "profile_background_tile": false,
    "profile_image_url": "http://a0.twimg.com/profile_images/314517279/adamrugel1_normal.jpg",
    "profile_image_url_https": "https://si0.twimg.com/profile_images/314517279/adamrugel1_normal.jpg",
    "profile_link_color": "0084B4",
    "profile_sidebar_border_color": "C0DEED",
    "profile_sidebar_fill_color": "DDEEF6",
    "profile_text_color": "333333",
    "profile_use_background_image": true,
    "protected": false,
    "screen_name": "Adam",
    "show_all_inline_media": true,
    "statuses_count": 3605,
    "time_zone": "Pacific Time (US & Canada)",
    "url": "http://www.trazzler.com",
    "utc_offset": -28800,
    "verified": false
  },
  {
    "contributors_enabled": false,
    "created_at": "Tue Mar 21 21:01:35 +0000 2006",
    "default_profile": false,
    "default_profile_image": false,
    "description": "Building Lift with @jcrosby, @mhendric, and @mattmatt.",
    "favourites_count": 691,
    "follow_request_sent": false,
    "followers_count": 13865,
    "following": false,
    "friends_count": 334,
    "geo_enabled": true,
    "id": 17,
    "id_str": "17",
    "is_translator": false,
    "lang": "en",
    "listed_count": 165,
    "location": "SF/NYC",
    "name": "Tony Stubblebine",
    "notifications": false,
    "profile_background_color": "ACDED6",
    "profile_background_image_url": "http://a0.twimg.com/images/themes/theme18/bg.gif",
    "profile_background_image_url_https": "https://si0.twimg.com/images/themes/theme18/bg.gif",
    "profile_background_tile": false,
    "profile_image_url": "http://a0.twimg.com/profile_images/1252541521/profile_photo_normal.jpg",
    "profile_image_url_https": "https://si0.twimg.com/profile_images/1252541521/profile_photo_normal.jpg",
    "profile_link_color": "038543",
    "profile_sidebar_border_color": "EEEEEE",
    "profile_sidebar_fill_color": "F6F6F6",
    "profile_text_color": "333333",
    "profile_use_background_image": true,
    "protected": false,
    "screen_name": "tonystubblebine",
    "show_all_inline_media": true,
    "status": {
      "contributors": null,
      "coordinates": null,
      "created_at": "Fri Jun 22 22:38:01 +0000 2012",
      "favorited": false,
      "geo": null,
      "id": 216299026289668096,
      "id_str": "216299026289668096",
      "in_reply_to_screen_name": "judsondunn",
      "in_reply_to_status_id": 216195690349600768,
      "in_reply_to_status_id_str": "216195690349600768",
      "in_reply_to_user_id": 12468,
      "in_reply_to_user_id_str": "12468",
      "place": null,
      "retweet_count": 0,
      "retweeted": false,
      "source": "web",
      "text": "@judsondunn want an invite? tony@lift.do",
      "truncated": false
    },
    "statuses_count": 4348,
    "time_zone": "Pacific Time (US & Canada)",
    "url": "http://www.stubbleblog.com",
    "utc_offset": -28800,
    "verified": false
  },
  {
    "contributors_enabled": false,
    "created_at": "Tue Mar 21 21:00:55 +0000 2006",
    "default_profile": false,
    "default_profile_image": false,
    "description": "Lacking pretense isn't always helpful in life.",
    "favourites_count": 353,
    "follow_request_sent": false,
    "followers_count": 10281,
    "following": false,
    "friends_count": 484,
    "geo_enabled": false,
    "id": 16,
    "id_str": "16",
    "is_translator": false,
    "lang": "en",
    "listed_count": 110,
    "location": "San Francisco",
    "name": "Jeremy",
    "notifications": false,
    "profile_background_color": "53545c",
    "profile_background_image_url": "http://a0.twimg.com/images/themes/theme2/bg.gif",
    "profile_background_image_url_https": "https://si0.twimg.com/images/themes/theme2/bg.gif",
    "profile_background_tile": false,
    "profile_image_url": "http://a0.twimg.com/profile_images/595850738/IMG_0594_normal.JPG",
    "profile_image_url_https": "https://si0.twimg.com/profile_images/595850738/IMG_0594_normal.JPG",
    "profile_link_color": "70a0db",
    "profile_sidebar_border_color": "e6e8eb",
    "profile_sidebar_fill_color": "16112b",
    "profile_text_color": "666666",
    "profile_use_background_image": false,
    "protected": false,
    "screen_name": "jeremy",
    "show_all_inline_media": false,
    "status": {
      "contributors": null,
      "coordinates": null,
      "created_at": "Tue Jun 19 00:37:43 +0000 2012",
      "favorited": false,
      "geo": null,
      "id": 214879600172478464,
      "id_str": "214879600172478464",
      "in_reply_to_screen_name": null,
      "in_reply_to_status_id": null,
      "in_reply_to_status_id_str": null,
      "in_reply_to_user_id": null,
      "in_reply_to_user_id_str": null,
      "place": null,
      "possibly_sensitive": false,
      "retweet_count": 19,
      "retweeted": false,
      "retweeted_status": {
        "contributors": null,
        "coordinates": null,
        "created_at": "Tue Jun 19 00:36:43 +0000 2012",
        "favorited": false,
        "geo": null,
        "id": 214879348321292289,
        "id_str": "214879348321292289",
        "in_reply_to_screen_name": null,
        "in_reply_to_status_id": null,
        "in_reply_to_status_id_str": null,
        "in_reply_to_user_id": null,
        "in_reply_to_user_id_str": null,
        "place": null,
        "possibly_sensitive": false,
        "retweet_count": 19,
        "retweeted": false,
        "source": "<a href=\"http://www.socialflow.com\" rel=\"nofollow\">SocialFlow</a>",
        "text": "Twitter slowly unfolding its search ambitions http://t.co/hzr9NBsf",
        "truncated": false
      },
      "source": "<a href=\"http://itunes.apple.com/us/app/twitter/id409789998?mt=12\" rel=\"nofollow\">Twitter for Mac</a>",
      "text": "RT @om: Twitter slowly unfolding its search ambitions http://t.co/hzr9NBsf",
      "truncated": false
    },
    "statuses_count": 4419,
    "time_zone": "Pacific Time (US & Canada)",
    "url": null,
    "utc_offset": -28800,
    "verified": false
  },
  {
    "contributors_enabled": false,
    "created_at": "Tue Mar 21 21:00:54 +0000 2006",
    "default_profile": false,
    "default_profile_image": false,
    "description": "",
    "favourites_count": 862,
    "follow_request_sent": false,
    "followers_count": 37427,
    "following": false,
    "friends_count": 262,
    "geo_enabled": true,
    "id": 15,
    "id_str": "15",
    "is_translator": false,
    "lang": "en",
    "listed_count": 518,
    "location": "San Francisco",
    "name": "crystal",
    "notifications": false,
    "profile_background_color": "C0DEED",
    "profile_background_image_url": "http://a0.twimg.com/profile_background_images/149112071/drumlin-2560x1600.jpg",
    "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/149112071/drumlin-2560x1600.jpg",
    "profile_background_tile": false,
    "profile_image_url": "http://a0.twimg.com/profile_images/1576199702/photo-1_normal.JPG",
    "profile_image_url_https": "https://si0.twimg.com/profile_images/1576199702/photo-1_normal.JPG",
    "profile_link_color": "0084B4",
    "profile_sidebar_border_color": "C0DEED",
    "profile_sidebar_fill_color": "DDEEF6",
    "profile_text_color": "333333",
    "profile_use_background_image": true,
    "protected": false,
    "screen_name": "crystal",
    "show_all_inline_media": true,
    "status": {
      "contributors": null,
      "coordinates": {
        "coordinates": [
          -118.48843932,
          34.00654807
        ],
        "type": "Point"
      },
      "created_at": "Fri Jun 22 02:52:31 +0000 2012",
      "favorited": false,
      "geo": {
        "coordinates": [
          34.00654807,
          -118.48843932
        ],
        "type": "Point"
      },
      "id": 216000685043486721,
      "id_str": "216000685043486721",
      "in_reply_to_screen_name": null,
      "in_reply_to_status_id": null,
      "in_reply_to_status_id_str": null,
      "in_reply_to_user_id": null,
      "in_reply_to_user_id_str": null,
      "place": {
        "attributes": {},
        "bounding_box": {
          "coordinates": [
            [
              [
                -118.55134,
                33.966674
              ],
              [
                -118.443426,
                33.966674
              ],
              [
                -118.443426,
                34.05056
              ],
              [
                -118.55134,
                34.05056
              ]
            ]
          ],
          "type": "Polygon"
        },
        "country": "United States",
        "country_code": "US",
        "full_name": "Santa Monica, CA",
        "id": "59612bd882018c51",
        "name": "Santa Monica",
        "place_type": "city",
        "url": "http://api.twitter.com/1/geo/id/59612bd882018c51.json"
      },
      "possibly_sensitive": false,
      "retweet_count": 0,
      "retweeted": false,
      "source": "<a href=\"http://foursquare.com\" rel=\"nofollow\">foursquare</a>",
      "text": "So looking forward to this dinner- to be in a wonderful place with wonderful friends is truly a blessing! #grateful http://t.co/w6v230N6",
      "truncated": false
    },
    "statuses_count": 12572,
    "time_zone": "Tijuana",
    "url": "http://t.co/roWLlkf",
    "utc_offset": -28800,
    "verified": false
  },
  {
    "contributors_enabled": false,
    "created_at": "Tue Mar 21 21:00:54 +0000 2006",
    "default_profile": false,
    "default_profile_image": false,
    "description": "i started this",
    "favourites_count": 17,
    "follow_request_sent": false,
    "followers_count": 24327,
    "following": false,
    "friends_count": 106,
    "geo_enabled": true,
    "id": 14,
    "id_str": "14",
    "is_translator": false,
    "lang": "en",
    "listed_count": 274,
    "location": "San Francisco",
    "name": "noah glass",
    "notifications": false,
    "profile_background_color": "ba030f",
    "profile_background_image_url": "http://a0.twimg.com/profile_background_images/2/flowers-and-logo.jpg",
    "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/2/flowers-and-logo.jpg",
    "profile_background_tile": false,
    "profile_image_url": "http://a0.twimg.com/profile_images/14019402/noahglass_normal.jpg",
    "profile_image_url_https": "https://si0.twimg.com/profile_images/14019402/noahglass_normal.jpg",
    "profile_link_color": "b62b3a",
    "profile_sidebar_border_color": "f62c47",
    "profile_sidebar_fill_color": "e1dfe0",
    "profile_text_color": "6f726e",
    "profile_use_background_image": true,
    "protected": false,
    "screen_name": "noah",
    "show_all_inline_media": false,
    "status": {
      "contributors": null,
      "coordinates": null,
      "created_at": "Fri Apr 15 00:20:47 +0000 2011",
      "favorited": false,
      "geo": null,
      "id": 58686168044281856,
      "id_str": "58686168044281856",
      "in_reply_to_screen_name": null,
      "in_reply_to_status_id": null,
      "in_reply_to_status_id_str": null,
      "in_reply_to_user_id": null,
      "in_reply_to_user_id_str": null,
      "place": null,
      "retweet_count": 14,
      "retweeted": false,
      "source": "<a href=\"http://twitter.com/devices\" rel=\"nofollow\">txt</a>",
      "text": "Delphine read the article aloud as I drove up hwy 1. Quite a welcome home!",
      "truncated": false
    },
    "statuses_count": 1175,
    "time_zone": "Pacific Time (US & Canada)",
    "url": "http://www.noahglass.com",
    "utc_offset": -28800,
    "verified": false
  },
  {
    "contributors_enabled": false,
    "created_at": "Tue Mar 21 20:51:43 +0000 2006",
    "default_profile": false,
    "default_profile_image": false,
    "description": "Co-founder of Twitter, Inc.",
    "favourites_count": 901,
    "follow_request_sent": false,
    "followers_count": 1920519,
    "following": false,
    "friends_count": 549,
    "geo_enabled": true,
    "id": 13,
    "id_str": "13",
    "is_translator": false,
    "lang": "en",
    "listed_count": 17174,
    "location": "San Francisco, CA",
    "name": "Biz Stone",
    "notifications": false,
    "profile_background_color": "022330",
    "profile_background_image_url": "http://a0.twimg.com/images/themes/theme15/bg.png",
    "profile_background_image_url_https": "https://si0.twimg.com/images/themes/theme15/bg.png",
    "profile_background_tile": false,
    "profile_image_url": "http://a0.twimg.com/profile_images/1749381351/image_normal.jpg",
    "profile_image_url_https": "https://si0.twimg.com/profile_images/1749381351/image_normal.jpg",
    "profile_link_color": "0084B4",
    "profile_sidebar_border_color": "a8c7f7",
    "profile_sidebar_fill_color": "C0DFEC",
    "profile_text_color": "333333",
    "profile_use_background_image": true,
    "protected": false,
    "screen_name": "biz",
    "show_all_inline_media": true,
    "status": {
      "contributors": null,
      "coordinates": null,
      "created_at": "Thu Jun 21 03:21:54 +0000 2012",
      "favorited": false,
      "geo": null,
      "id": 215645693971406848,
      "id_str": "215645693971406848",
      "in_reply_to_screen_name": null,
      "in_reply_to_status_id": null,
      "in_reply_to_status_id_str": null,
      "in_reply_to_user_id": null,
      "in_reply_to_user_id_str": null,
      "place": null,
      "possibly_sensitive": false,
      "retweet_count": 66,
      "retweeted": false,
      "source": "web",
      "text": "Here's a great idea for the city of San Francisco https://t.co/VlRbbU6O",
      "truncated": false
    },
    "statuses_count": 4911,
    "time_zone": "Pacific Time (US & Canada)",
    "url": "http://t.co/bdlNWgB",
    "utc_offset": -28800,
    "verified": true
  },
  {
    "contributors_enabled": true,
    "created_at": "Tue Mar 21 20:50:14 +0000 2006",
    "default_profile": false,
    "default_profile_image": false,
    "description": "Executive Chairman of Twitter, CEO of Square, a founder of both.",
    "favourites_count": 1047,
    "follow_request_sent": false,
    "followers_count": 2026858,
    "following": false,
    "friends_count": 1192,
    "geo_enabled": true,
    "id": 12,
    "id_str": "12",
    "is_translator": false,
    "lang": "en",
    "listed_count": 18035,
    "location": "San Francisco",
    "name": "Jack Dorsey",
    "notifications": false,
    "profile_background_color": "EBEBEB",
    "profile_background_image_url": "http://a0.twimg.com/images/themes/theme7/bg.gif",
    "profile_background_image_url_https": "https://si0.twimg.com/images/themes/theme7/bg.gif",
    "profile_background_tile": false,
    "profile_image_url": "http://a0.twimg.com/profile_images/1563216547/image_normal.jpg",
    "profile_image_url_https": "https://si0.twimg.com/profile_images/1563216547/image_normal.jpg",
    "profile_link_color": "990000",
    "profile_sidebar_border_color": "DFDFDF",
    "profile_sidebar_fill_color": "F3F3F3",
    "profile_text_color": "333333",
    "profile_use_background_image": true,
    "protected": false,
    "screen_name": "jack",
    "show_all_inline_media": true,
    "status": {
      "contributors": null,
      "coordinates": null,
      "created_at": "Fri Jun 22 06:27:29 +0000 2012",
      "favorited": false,
      "geo": null,
      "id": 216054784015335425,
      "id_str": "216054784015335425",
      "in_reply_to_screen_name": null,
      "in_reply_to_status_id": null,
      "in_reply_to_status_id_str": null,
      "in_reply_to_user_id": null,
      "in_reply_to_user_id_str": null,
      "place": null,
      "retweet_count": 34538,
      "retweeted": false,
      "retweeted_status": {
        "contributors": null,
        "coordinates": null,
        "created_at": "Fri Jun 22 05:54:32 +0000 2012",
        "favorited": false,
        "geo": null,
        "id": 216046493721825280,
        "id_str": "216046493721825280",
        "in_reply_to_screen_name": null,
        "in_reply_to_status_id": null,
        "in_reply_to_status_id_str": null,
        "in_reply_to_user_id": null,
        "in_reply_to_user_id_str": null,
        "place": null,
        "retweet_count": 34538,
        "retweeted": false,
        "source": "<a href=\"http://www.echofon.com/\" rel=\"nofollow\">Echofon</a>",
        "text": "Tough way to end a season but I am truly blessed to have the privilege to play for such a great city, congrats to the Miami Heat..",
        "truncated": false
      },
      "source": "<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
      "text": "RT @KDTrey5: Tough way to end a season but I am truly blessed to have the privilege to play for such a great city, congrats to the Miami ...",
      "truncated": true
    },
    "statuses_count": 11242,
    "time_zone": "Pacific Time (US & Canada)",
    "url": null,
    "utc_offset": -28800,
    "verified": true
  }
]

'''
